### ISSUE TITLE
Import all HRV values from sleep not only average ( please)

### ISSUE THREAD

**Issue by aintnogeek** [James-2879/OuraAppleHealth#3]
I want to see all data of HRV each measurement in apple health from oura ring from overnight sleep

**Comment by kilooo** [comment]
Looking for this feature as well. I played around with the API and it looks like you do get all the hrv information. Just don’t know how to go about formatting it and importing it to the health app.

**Comment by exhibiton** [comment]
I went ahead and did this. I am testing apps like [Bevel](https://bevel.health) which prefer to know all of the data instead of just one HRV value.

Here is the Shortcut: https://www.icloud.com/shortcuts/b5b152c7a9d543b6ac56f2995864b0c5 @James-2879 can add it into the repository if he sees it as a valuable addition.

**Comment by James-2879** [comment]
@exhibiton Looks good, if you want to make a PR I'll merge it. If not I'll add it in when I have some time.

**Comment by exhibiton** [comment]
Done!
